name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GCC and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc g++

    - name: Install dependencies
      run:  |
        sudo apt-get update
        sudo apt-get install -y build-essential

# Make matrix multiplication executables

    - name: Build Mat-mul Serial Implementation
      run: |
        cd src/
        make serial_mul
        cd ..

    - name: Build Mat-mul Pthreads implementation
      run: |
        cd src/
        make pthread_mul
        cd ..

    - name: Build Mat-mul OpenMP Implementation
      run: |
        cd src/
        make openmp_mul
        cd ..

# Make graph minor calculation executables

    - name: Build Graph Minor Serial Implementation
      run: |
        cd src/
        make serial_gm
        cd ..

    - name: Build Graph Minor Pthreads implementation
      run: |
        cd src/
        make pthread_gm
        cd ..

    - name: Build Graph Minor OpenMP Implementation
      run: |
        cd src/
        make openmp_mul
        cd ..

# Run tests
    - name: Run Tests
      run:  |
        cd tests/
        ./validate_openmp_runtime.sh

